### ISSUE TITLE
Links on blue buttons get "invisible" after first visit 

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/inveniosoftware.org#172]
Package version (if known): https://inveniosoftware.org/products/rdm/ 2022-09-07

## Describe the bug
When clicking on some buttons to open the underlying links in a new tab the text color changes to something not readable.

## Steps to Reproduce
1. Go to https://inveniosoftware.org/products/rdm/
2. Scroll down to "Project Information"
4. Click right on the button "Roadmap"
5. Open the link in a new tab OR just move your cursor a bit around
6. See the text of the button vanish when not in the button area

## Expected behavior

Text color shouldn't change.

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/74763324/188872493-0b2296bc-87b1-4d64-921a-e7e3417d6f52.png)

**Comment by chriz-uniba** [comment]
I forgot to add some maybe interesting details:

```
$ firefox --version
Mozilla Firefox 91.13.0esr
```

```
$ uname -a
Linux x 5.18.0-0.deb11.3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.14-1~bpo11+1 (2022-07-28) x86_64 GNU/Linux
```

**Comment by avivace** [comment]
This is happening to me too, on both Firefox and Chromium

![image](https://github.com/inveniosoftware/inveniosoftware.org/assets/14352721/3eb36592-f36f-4779-8fd6-5aff41d7ba05)

```
> chromium --version
Chromium 113.0.5672.126 built on Debian 12.0, running on Debian 12.0
> firefox --version
Mozilla Firefox 113.0
> uname -a
Linux x 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux
```

**Comment by ptamarit** [comment]
Thanks a lot @chriz-uniba and @avivace for reporting this problem, and sorry for having taken so long to address it.

A bugfix was just merged and I confirm that the problem is now fixed.
Since GitHub pages does not allow for proper cache invalidation of HTML files, you will probably need to refresh in order to fetch the latest CSS containing the fix.

Do not hesitate to let us know here in case the problem persists.
