### ISSUE TITLE
Move invenio v1.x files from /download/ into repository

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/inveniosoftware.org#50]

**Comment by tiborsimko** [comment]
The amount of stuff is 7GB, so having it in a repository may not be practical.

What about creating a separate website (with files hosted on CERN AFS/DFS) such as:

- `invenio1.cern.ch/download`
- `legacy.inveniosoftware.org/download`
-  `invenio1.inveniosoftware.org/download`
- `download.inveniosoftware.org`

The site does not have to be publicised, since Invenio 1 is kind of deprecated in favour of Invenio 3
We could just instruct people who would still need to access `http://invenio-software.org/download/...` files to replace the URL by `http://invenio1.cern.ch/download/...`.

**Comment by lnielsen** [comment]
Let's go for an static EOS hosted website? I would go for either a cern.ch domain (thus no need for DNS update) or ``download.inveniosoftware.org`` (since we anyway likely have to update the DNS and can do it in one go). WDYT?

**Comment by tiborsimko** [comment]
The static EOS web site done, reusing the old `cern.ch/inveniosoftware` web site instance.  It contains only two things:

- a simple `index.html` for casual visitors who might appear there by mishap (but see below);
- the full content of the legacy `download` directory.

An example of old path: 

- `http://inveniosoftware.org/download/invenio-1.2.2.tar.gz.sig`
- `http://inveniosoftware.org/download/aaa/bbb/ccc/ddd.ext`

Corresponding new paths:

- `http://inveniosoftware.web.cern.ch/inveniosoftware/download/invenio-1.2.2.tar.gz.sig`
- `http://inveniosoftware.web.cern.ch/inveniosoftware/download/aaa/bbb/ccc/ddd.ext`

We could expose these under `download.inveniosoftware.org` indeed... But let's also see where we shall host the main Invenio project web site. (Currently it is self-hosted on a `inveniosoftware.cern.ch` VM using Docker.) Some options:  (i) host it as wel on the same EOS site? (ii) host it on CERN OpenShift? (iii) host it on GitHub Pages? Let's muse IRL.

P.S. For the REANA project web site I went with the option (ii) for now, to retain a possibility to deploy some dynamic services later.

**Comment by lnielsen** [comment]
Do you know if there's any possibility to get rid of path part (``/inveniosoftware/``)?

**Comment by tiborsimko** [comment]
Not that I know of, judging by past experiences... I can double-confirm. (This is also why I usually prefer other hosting techniques...)

**Comment by lnielsen** [comment]
Closing as done - remaining part of documenting the new URL is part of #69
